### ISSUE TITLE
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#386]
org.json.JSONException: Value (JSONObject.java:158)
at org.json.JSONObject.<init>(JSONObject.java:171)
at org.digitalcampus.mobile.learning.task.SubmitTrackerTask.doInBackground(SubmitTrackerTask.java:93)
at org.digitalcampus.mobile.learning.task.SubmitTrackerTask.doInBackground(SubmitTrackerTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)

**Comment by alexlittle** [comment]
Not seen error for long time - so assuming no longer an issue
