### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in authority at index 29: http://oppia.dreamhosters.com api/v1/tracker/

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#387]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:278)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 29: http://oppia.dreamhosters.com api/v1/tracker/
at java.net.URI.create(URI.java:727)
at org.apache.http.client.methods.HttpPatch.<init>(HttpPatch.java:67)
at org.digitalcampus.oppia.task.SubmitTrackerMultipleTask.doInBackground(SubmitTrackerMultipleTask.java:60)
at org.digitalcampus.oppia.task.SubmitTrackerMultipleTask.doInBackground(SubmitTrackerMultipleTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 5 more

**Comment by alexlittle** [comment]
Haven;t seen this error for long time, so assuming resolved
