### ISSUE TITLE
Not connecting to get course download list

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#418]
Is providing report to user that it can't connect to the internet - but think this message is misleading as seems this is the actual error:

java.lang.NullPointerException
at org.digitalcampus.oppia.activity.TagSelectActivity.onSaveInstanceState(TagSelectActivity.java:108)
at android.app.Activity.performSaveInstanceState(Activity.java:1173)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3192)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3256)
at android.app.ActivityThread.access$1100(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1230)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5118)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)

**Comment by alexlittle** [comment]
Was happening on an LG 3g S - using app version 5.0.1
