### ISSUE TITLE
Better error handling if disk is full

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#530]
Currently if the disk is full then the app will just crash (unsurprisingly), but could be handled better - eg showing a message to the user that they should look at removing some music/photos etc. This crashing may be happening when app is in the background (eg on tracker submission and updating db).

Stack trace:

android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
1   at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
2   at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:968)
3   at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
4   at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
5   at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1575)
6   at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1471)
7   at org.digitalcampus.oppia.application.DbHelper.insertTracker(DbHelper.java:588)
8   at org.digitalcampus.oppia.application.Tracker.saveTracker(Tracker.java:45)
9   at org.digitalcampus.oppia.widgets.PageWidget.saveTracker(PageWidget.java:237)
10  at org.digitalcampus.oppia.activity.CourseActivity.onTabUnselected(CourseActivity.java:302)
11  at com.android.internal.app.ActionBarImpl.selectTab(ActionBarImpl.java:618)
12  at com.android.internal.app.ActionBarImpl$TabImpl.select(ActionBarImpl.java:1140)
13  at com.android.internal.widget.ScrollingTabContainerView$TabClickListener.onClick(ScrollingTabContainerView.java:695)
14  at android.view.View.performClick(View.java:4452)
15  at android.view.View$PerformClick.run(View.java:18428)
16  at android.os.Handler.handleCallback(Handler.java:725)
17  at android.os.Handler.dispatchMessage(Handler.java:92)
18  at android.os.Looper.loop(Looper.java:176)
19  at android.app.ActivityThread.main(ActivityThread.java:5365)
20  at java.lang.reflect.Method.invokeNative(Native Method)
21  at java.lang.reflect.Method.invoke(Method.java:511)
22  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
23  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
24  at dalvik.system.NativeStart.main(Native Method)

**Comment by alexlittle** [comment]
transferred to OPPIA-127
