### ISSUE TITLE
OppiaMobile Core (5.6): java.io.FileNotFoundException

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#558]
Not sure if this is something to do with the new permissions in Android 6?

Likely to have happened when someone clicks on the "download via PC" option on the download media page.

Error Message

java.io.FileNotFoundException: /storage/sdcard0/mobile-learning-media.html: open failed: EACCES (Permission denied)

Where

DownloadMediaActivity.java:157

Short Stacktrace
0   java.io.FileNotFoundException: /storage/sdcard0/mobile-learning-media.html: open failed: EACCES (Permission denied)
1   at libcore.io.IoBridge.open(IoBridge.java:409)
2   at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
3   at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
4   at org.digitalcampus.oppia.activity.DownloadMediaActivity.downloadViaPC(DownloadMediaActivity.java:157)
5   at org.digitalcampus.oppia.activity.DownloadMediaActivity.access$2(DownloadMediaActivity.java:139)
6   at org.digitalcampus.oppia.activity.DownloadMediaActivity$1.onClick(DownloadMediaActivity.java:95)
7   at android.view.View.performClick(View.java:4240)
8   at android.view.View$PerformClick.run(View.java:17749)
9   at android.os.Handler.handleCallback(Handler.java:730)
10  at android.os.Handler.dispatchMessage(Handler.java:92)
11  at android.os.Looper.loop(Looper.java:137)
12  at android.app.ActivityThread.main(ActivityThread.java:5457)
13  at java.lang.reflect.Method.invokeNative(Native Method)
14  at java.lang.reflect.Method.invoke(Method.java:525)
15  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:854)
16  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
17  at dalvik.system.NativeStart.main(Native Method)
18  Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
19  at libcore.io.Posix.open(Native Method)
20  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
21  at libcore.io.IoBridge.open(IoBridge.java:393)
22  ... 16 more
Tag
log
Affected App Versions

5.6
Affected OS Versions

4.3

**Comment by alexlittle** [comment]
Closed as not an issue on current version of app
