### ISSUE TITLE
App crashing issues on password reset and video download

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#610]
On both these tasks, the app crashes. Very similar to the login carshing we had the other day - so suspect that it may be the same cause/issue

**Comment by alexlittle** [comment]
media download error is as follows:

FATAL EXCEPTION: main
                                                                              Process: org.intrahealth.zambia.oppia, PID: 11616
                                                                              java.lang.RuntimeException: Error receiving broadcast Intent { act=com.digitalcampus.oppia.DOWNLOADSERVICE flg=0x10 (has extras) } in org.digitalcampus.oppia.service.DownloadBroadcastReceiver@2f16ac
                                                                                  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
                                                                                  at android.os.Handler.handleCallback(Handler.java:746)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=3
                                                                                  at android.util.SparseBooleanArray.keyAt(SparseBooleanArray.java:165)
                                                                                  at org.digitalcampus.oppia.activity.DownloadMediaActivity.onDownloadComplete(DownloadMediaActivity.java:383)
                                                                                  at org.digitalcampus.oppia.service.DownloadBroadcastReceiver.onReceive(DownloadBroadcastReceiver.java:44)
                                                                                  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
                                                                                  at android.os.Handler.handleCallback(Handler.java:746) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
