### ISSUE TITLE
Possible bug: android.os.FileUriExposedException: file exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#805]
I got an automated bug report from the OpenDeliver app, not sure if this also applies to the core app too, but something that should be looked at at some point.

android.os.FileUriExposedException: file:///data/user/0/org.opendeliver.oppia/files/modules/anc1-all/images/0f45f7774a3edaa59b74f18b6bf5a5adbd4f4810 exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
	at android.app.Activity.startActivityForResult(Activity.java:4516)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4474)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4835)
	at android.app.Activity.startActivity(Activity.java:4803)
	at org.digitalcampus.oppia.widgets.QuizWidget$OnImageClickListener.onClick(QuizWidget.java:716)
	at android.view.View.performClick(View.java:6726)
	at android.view.View$PerformClick.run(View.java:25434)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by jbc25** [comment]
It seems someone solved it already. It was an issue happening in devices above Android Nougat version, where sharing with external apps system changed.
But it is updated now in code and working after some testing

**Comment by alexlittle** [comment]
Thanks @jbc25  - I think the Open Deliver app hasn't been updated for a little while now, so I wasn;t sure if it was an issue int he core version too
