### ISSUE TITLE
"java.lang.RuntimeException: Unable to start receiver" error message

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#854]
I'm getting a few automated emails with the same error (just on the LMH app though). Unclear to me if this causes the app to crash too - but it looks like it might just be a background error?

The full stack trace is:
java.lang.RuntimeException: Unable to start receiver org.digitalcampus.oppia.service.TrackerStartServiceReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.lastmilehealth.oppiamobile/org.digitalcampus.oppia.service.TrackerService (has extras) }: app is in background uid UidRecord{61ccde6 u0a224 RCVR bg:+3m37s761ms idle change:uncached procs:1 seq(7576,7576,7576)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3523)
	at android.app.ActivityThread.access$1400(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1759)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.lastmilehealth.oppiamobile/org.digitalcampus.oppia.service.TrackerService (has extras) }: app is in background uid UidRecord{61ccde6 u0a224 RCVR bg:+3m37s761ms idle change:uncached procs:1 seq(7576,7576,7576)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
	at android.app.ContextImpl.startService(ContextImpl.java:1550)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at org.digitalcampus.oppia.service.TrackerStartServiceReceiver.onReceive(TrackerStartServiceReceiver.java:44)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3507)
	... 8 more

**Comment by alexlittle** [comment]
See also: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by alexlittle** [comment]
This info was included in the automated bug report...

OS | Android 9
App Version | 6.8.0
Device | OnePlus ONEPLUS A6013

hope this helps?
