### ISSUE TITLE
ListPreference requires an entries array and an entryValues array

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#886]
From an automated bug report on LMH (v7.0.0), but unclear exactly action what generated the error:
java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
	at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:249)
	at android.preference.DialogPreference.showDialog(DialogPreference.java:306)
	at android.preference.DialogPreference.onClick(DialogPreference.java:277)
	at android.preference.Preference.performClick(Preference.java:1135)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by jbc25** [comment]
This problem was not only a bug, was related with the bussiness logic
