### ISSUE TITLE
TransactionTooLargeException: data parcel size

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#924]
I had this from an automated bug report on the LMH app. Unclear to me exactly what might have caused this issue though.

Stack trace:
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1052568 bytes
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 1052568 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1177)
	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3969)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
	... 7 more

**Comment by alexlittle** [comment]
duplicate of #961
