### ISSUE TITLE
Test `BuildChecksOppiaCore` regularly fails

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#947]
If the app is uninstalled then reinstalled, the test passes. However if the app is not uninstalled first the test fails.

**Comment by jbc25** [comment]
Could you attach the detail of the error?

**Comment by alexlittle** [comment]
hmmm... now I can't recreate this... it happened the other day (and had happened when we were in Alcala), but I;ve tried running the tests as both fresh and update installs on my physical device and AVD - but can;t get it to appear again.

I'll close for now, but can re-open if I see it happen again, and will attach the extra info

**Comment by jjoseba** [comment]
It was happening for me in the `v7.0.3` branch before commit 5fda2c43441b67f9100c263a2ee37fbdb76fda1c
That one solved the problem. Maybe it was wrong before because it can be confusing what it is checking, it previously had the current version number instead of the override password number set in the properties file.

**Comment by jbc25** [comment]
Yes, this number is going to change regularly. Maybe we can skip this check.
Anyway I remember @alexlittle has another problem. But if it is not happening now maybe it was fixed. Let see if it appears again.

**Comment by alexlittle** [comment]
Thanks @jbc25  - though I'm not sure this number should be changing that often... it should only change when we want to force the admin password to be changed to a new value (so not every app release - I hope at least!)

**Comment by jbc25** [comment]
Ok, then we have to be aware to change the test when this number is updated. Maybe we can place a comment in the properties file beside this parameter

**Comment by alexlittle** [comment]
Yes we can add a message in the props, although we should be running all the tests before an app is built/deployed so it will be highlighted then that the number in the test hasn't been updated

**Comment by alexlittle** [comment]
I had this issue occur just now (on the v7.0.3 branch with the latest PRs), so the full output is as below and am reopening:

java.lang.AssertionError: expected:<null> but was:<https://demo.oppia-mobile.org/>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at BuildChecksOppiaCore.checkDefaultSettingsParameters(BuildChecksOppiaCore.java:37)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)

E/TestRunner: failed: checkDefaultSettingsParameters(BuildChecksOppiaCore)
    ----- begin exception -----
E/TestRunner: java.lang.AssertionError: expected:<null> but was:<https://demo.oppia-mobile.org/>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at BuildChecksOppiaCore.checkDefaultSettingsParameters(BuildChecksOppiaCore.java:37)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)

**Comment by alexlittle** [comment]
It happens on both my physical device and AVD, when there is a version of the app already installed

**Comment by alexlittle** [comment]
transferred to OPPIA-205
