### ISSUE TITLE
Several AdminProtection tests fail and hangs rest of test suite

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#973]
These ones:

- checkAdminProtectionOnManageCoursesClick
- checkAdminProtectionToEnterSettingsScreen
- checkAdminProtectionOnGlobalScorecardManageCoursesClick
- checkAdminProtectionOnCourseOptionsClick

The full output is below, but I've had to comment out the test for now as it makes all the rest of the tests hang

java.lang.reflect.UndeclaredThrowableException
at $Proxy14.getUser(Unknown Source)
at org.digitalcampus.oppia.activity.MainActivity.updateUserTotalPoints(MainActivity.java:140)
at org.digitalcampus.oppia.activity.MainActivity.onResume(MainActivity.java:134)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnResume(MonitoringInstrumentation.java:734)
at android.app.Activity.performResume(Activity.java:7292)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at it.cosenonjaviste.daggermock.ComponentOverrider$1.answer(ComponentOverrider.java:49)
at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:93)
at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
at com.google.dexmaker.mockito.InvocationHandlerAdapter.invoke(InvocationHandlerAdapter.java:49)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
... 18 more
Caused by: java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
at org.digitalcampus.oppia.di.AppModule_ProvideUserFactory.get(AppModule_ProvideUserFactory.java:22)
at org.digitalcampus.oppia.di.AppModule_ProvideUserFactory.get(AppModule_ProvideUserFactory.java:8)
at org.digitalcampus.oppia.di.DaggerAppComponent.getUser(DaggerAppComponent.java:253)
... 25 more

**Comment by jbc25** [comment]
@alexlittle could you try only this new class of test after login with your user in the app?
Also check you have internet and a working server. 
If this work we have to review the tests to make them more independent

**Comment by alexlittle** [comment]
I tried just running these tests and the full output is attached
[output.txt](https://github.com/DigitalCampus/oppia-mobile-android/files/3991321/output.txt)

I also started a new branch to work on this - issue-973-adminprotected-tests

**Comment by alexlittle** [comment]
Ah I realise that the tests only pass when a user is logged in. Which is kinda OK for when we're testing locally (and we remember to log in first), but it's going to be a problem with the github workflow yml as we won't have the ability to log the user in first. 

So the test should be updated so that it logs the user in too...
