### ISSUE TITLE
App crashing when using back icon in course page

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#982]
I've been testing v7.0.3 of the Academy app, and I keep getting an error message when I use the back arrow in the top left corner to navigate back to the home page from the course list. The error says 'Unfortunately, Academy has stopped'. When I click 'Ok' I'm taken back to the home page, so the app isn't crashing, but I tried restarting the app and the phone and continue to see the error message every time I try to navigate back from the course list.

- [ ] fix the bug
- [ ] add a test for this

**Comment by alexlittle** [comment]
Stacktrace message is...

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lastmilehealth.oppiamobile/org.digitalcampus.oppia.activity.CourseMetaPageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.digitalcampus.oppia.model.Lang org.digitalcampus.oppia.model.CourseMetaPage.getLang(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.digitalcampus.oppia.model.Lang org.digitalcampus.oppia.model.CourseMetaPage.getLang(java.lang.String)' on a null object reference
	at org.digitalcampus.oppia.activity.CourseMetaPageActivity.onCreate(CourseMetaPageActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	... 11 more
